
auto-feed:
  camera:
    cmd: sleep 100000
    cmd_force: echo $0
  sound:
    path: /Users/mathieu/Programmation/Workspace/auto-feed-rest-api/src/main/resources/sounds/apple_sms_crop2.wav
  tasks:
    sound:
      repeat: 3