
auto-feed:
  camera:
    cmd: /product/auto-feed/auto-feed/scripts/start_camera.ksh
    cmd_force: /product/auto-feed/auto-feed/scripts/force_kill_camera.ksh
  sound:
    path: /product/auto-feed/auto-feed/config/sounds/apple_sms_crop2.wav
  tasks:
    sound:
      repeat: 3